# URL Server
#client.URL = http://localhost:3000
client.URL = https://trananhthi.id.vn
#context-path
server.servlet.context-path=/facebook

# config server
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Config Hibernate
spring.jpa.open-in-view = false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#Data source local
ds.username = root
ds.password = thi2522002
ds.url = jdbc:mysql://localhost:3306/facebook?serverTimezone=Asia/Ho_Chi_Minh

#Data source AWS
#ds.username = admin
#ds.password = thi2522002
#ds.url = jdbc:mysql://web-server-database.clae8c80oh7c.ap-southeast-1.rds.amazonaws.com:3306/facebook?serverTimezone=Asia/Ho_Chi_Minh


spring.jackson.time-zone=Asia/Ho_Chi_Minh

#AWS
aws.accessKey=FKN6BT7K0LQ1YBE81MQX
aws.secretKey=k4F0ibxy3Th40eoaxCNQaXqC7MXFtr8QV81V504E

#Config S3 Storage
aws.s3.endpoint=https://s3-hcm-r1.longvan.net
aws.s3.region=ap-southeast-1

# Config MongoDB
spring.data.mongodb.uri=mongodb+srv://trananhthi56:thi2522002@mongodb-thi.ncrxvjo.mongodb.net/facebook?retryWrites=true&w=majority

# Config Redis Cloud
#spring.redis.host=redis-16190.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
#spring.redis.port=16190

# Config Redis Local
spring.redis.host=127.0.0.1
spring.redis.port=6379

# config ssl
#server.port=8443
#server.ssl.key-store=classpath:mydomain.p12
#server.ssl.key-store-password=2522002
#server.ssl.keyStoreType=PKCS12
#server.ssl.keyAlias=trananhthi
#server.ssl.key-password=2522002

# Config throw exception if no handler found
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Config message source
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600


